### PR TITLE
Add libssl1.1 for samp and openmp

### PR DESCRIPTION
**Pull request by QuintenQVD0**
### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by gOOvER** [comment]
Libssl 1.1 is eol and should not longer be used

And 32 bit also. The devs should fix that.

**Comment by QuintenQVD0** [comment]
> Libssl 1.1 is eol and should not longer be used
> 
> And 32 bit also. The devs should fix that.

I know but old games need old packages ...

**Comment by gOOvER** [comment]
> > Libssl 1.1 is eol and should not longer be used
> > And 32 bit also. The devs should fix that.
> 
> I know but old games need old packages ...

Or a dev, which fix this. Just my 2 cents now; GTA-SA is dead and why keep it alive?

**Comment by gOOvER** [comment]
open a Bug Request here, to support libssl 3

https://github.com/openmultiplayer/launcher/issues

**Comment by gOOvER** [comment]
> open a Bug Request here, to support libssl 3 https://github.com/openmultiplayer/launcher/issues
> 
> i would stop supporting samp and onyl take a look to openmp, since openmp have a active development. Now its wasted time to rewrite all for such old/abdoned games

**Comment by QuintenQVD0** [comment]
> open a Bug Request here, to support libssl 3 https://github.com/openmultiplayer/launcher/issues
> 
> i would stop supporting samp and onyl take a look to openmp, since openmp have a active development. Now its wated time to rewrite all for such old games

This patch is for openmp?

**Comment by gOOvER** [comment]
> > open a Bug Request here, to support libssl 3 https://github.com/openmultiplayer/launcher/issues
> > i would stop supporting samp and onyl take a look to openmp, since openmp have a active development. Now its wated time to rewrite all for such old games
> 
> This patch is for openmp?

i see no patch yet for ssl3

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
