### PR TITLE
Add RCon Client for DayZ image

### PR DESCRIPTION
**Pull request by shaynendradika**
## Description

Added rcon client installation for DayZ image. This will provide a rcon client for Battleye protocol which is used by DayZ and Arma series.

### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Wy this and not the client we use in litterly all other images?

**Comment by shaynendradika** [comment]
I've tried on my localhost using rcon-cli (the one that you use on all other images), however it doesn't work on Battleye RCon Protocol, and only support Source RCon Procotol. It is also described in [rcon-cli README.md](https://github.com/gorcon/rcon-cli/blob/master/README.md).

**Comment by gOOvER** [comment]
as i know, there isnt any similar for Battleye RCon Protocol

**Comment by gOOvER** [comment]
ohh found sth new

https://github.com/WoozyMasta/bercon

**Review by QuintenQVD0 — APPROVED** [review]
LGTM

**Pull request merged**
